# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [1]:
import torch

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

In [4]:
t = torch.tensor([[1, 2] , [3, 4], [5, 6]])

print(t)

# додеалть чтоб было три измерения

print(t.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])


In [5]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
4 * torch.eye(4)

tensor([[4., 0., 0., 0.],
        [0., 4., 0., 0.],
        [0., 0., 4., 0.],
        [0., 0., 0., 4.]])

In [8]:
torch.arange(100).reshape(10, 10) + torch.ones(1, 10) * 2 

tensor([[  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.],
        [ 12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.],
        [ 22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.],
        [ 32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.],
        [ 42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.],
        [ 52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.],
        [ 62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.],
        [ 72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.],
        [ 82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.],
        [ 92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101.]])

In [9]:
t = torch.arange(100).reshape(10, 10)
print(t)
print("------------------------")

t[2:5:, ::2]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
------------------------


tensor([[20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]])

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [10]:
t = torch.zeros(8, 8)
t[0] = torch.tensor([-4., -3., -2., -6., -5., -2., -3., -4.])
t[-1] = t[0] * -1
t[1] = -1 * torch.ones(1, 8)
t[-2] = t[1] * -1
t

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [11]:
result = 1
for i in range(2, 21, 2):
    result *= torch.tensor(i * (i + 1))

print(result)

tensor(-4249290049419214848)


This code iterates over the even numbers from 2 to 20 (incrementing by 2 each time), and calculates the product of each even number with the nearest larger odd number (which is simply i + 1 in this case). The result of the calculation is then converted to a PyTorch tensor using the torch.tensor function, and the final result is printed.

In [12]:
even_numbers = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
odd_numbers = even_numbers + 1
products = even_numbers * odd_numbers
result = products.prod()

print(result)

tensor(-4249290049419214848)


In this code, the even numbers from 2 to 20 are first created as a PyTorch tensor even_numbers. The nearest larger odd numbers are then calculated as odd_numbers by adding 1 to even_numbers. The product of each even and odd number is then calculated as products, and the final result is obtained using the prod() method which computes the product of all elements in a tensor. The final result is then printed.

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
torch.arange(1, 111).reshape(11, 10)[::, :7:]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

In [13]:
import torch

row = torch.arange(1, 8)
rows = torch.stack([row + 10 * i for i in range(11)])
result = rows

print(result)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])


In this code, the first row [1, 2, 3, ..., 7] is created as a PyTorch tensor row using the arange function. This row is then duplicated and shifted by multiples of 10 to obtain all the other rows. The final result is a 11x7 tensor rows obtained by stacking all the rows together using the stack function. The final result is then assigned to result and printed.

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [15]:
# repeat

n, m = 4, 5

mask = torch.tensor([[0, 1], [2, 3]])
mask.repeat(n, m)[:n:, :m:]

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

In [16]:
torch.rand(4, 7) * 20

tensor([[ 2.6004, 17.8714,  5.2814, 13.1778,  0.0863, 10.7123, 15.6352],
        [14.5975,  7.9949, 19.0173, 16.6113, 14.7790,  9.6055,  5.4613],
        [ 7.0817, 14.1338, 19.3629, 18.5898,  0.1182,  5.8272, 14.3032],
        [ 8.3938, 12.0178,  7.2631,  3.1794, 17.8672,  7.4463,  3.7385]])

In [17]:
t = torch.rand(4, 7) * 20
# минимальный элемент
m = t.min()
# максимальный элемент
M = t.max()

a = 1 / (M - m)
b = - a * m

print(t)

print("--------------------")


a * t + b

tensor([[ 5.8110,  5.4652,  3.7018, 13.3905, 15.4007, 17.6152, 19.1630],
        [ 6.1315, 12.4170,  4.6050,  9.6391, 14.4015, 19.4954,  2.7333],
        [ 4.7953, 18.8907,  1.3069, 19.8483, 13.5290,  2.9319,  5.2205],
        [10.2639,  9.9273, 14.9006,  2.2942, 11.5458, 11.6736, 17.0557]])
--------------------


tensor([[0.2429, 0.2243, 0.1292, 0.6517, 0.7601, 0.8796, 0.9630],
        [0.2602, 0.5992, 0.1779, 0.4494, 0.7062, 0.9810, 0.0769],
        [0.1881, 0.9484, 0.0000, 1.0000, 0.6592, 0.0876, 0.2111],
        [0.4831, 0.4649, 0.7332, 0.0532, 0.5522, 0.5591, 0.8494]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [18]:
torch.randint(0, 11, (4, 7))

tensor([[ 1,  3, 10,  8,  5, 10,  5],
        [ 1,  2,  8,  3,  7,  3,  1],
        [ 5,  0,  6,  3,  4,  8,  3],
        [ 1,  4,  5,  0, 10,  5, 10]])

In [19]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))

print(ar1)
print("---------------")
print(ar2)



tensor([[ 9,  2, 10,  4,  0,  4,  8],
        [ 7,  3,  9,  8,  8,  9,  3],
        [ 1,  5,  5, 10,  2,  1, 10],
        [ 0,  1,  3,  4,  6,  8,  1]])
---------------
tensor([[ 2,  6,  5,  2,  0,  0,  0],
        [ 7,  3,  3,  3,  4,  4,  7],
        [ 6,  6,  6,  3,  5,  3,  7],
        [ 6,  7,  9,  8,  6,  8, 10]])


In [20]:
ar2 * (ar1 < ar2)

tensor([[ 0,  6,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  7],
        [ 6,  6,  6,  0,  5,  3,  0],
        [ 6,  7,  9,  8,  0,  0, 10]])

In [21]:
ar2 * (ar1 < ar2) + ar1 * (ar1 >= ar2)

tensor([[ 9,  6, 10,  4,  0,  4,  8],
        [ 7,  3,  9,  8,  8,  9,  7],
        [ 6,  6,  6, 10,  5,  3, 10],
        [ 6,  7,  9,  8,  6,  8, 10]])

In [22]:
ar1 * (ar1 >= ar2)

tensor([[ 9,  0, 10,  4,  0,  4,  8],
        [ 7,  3,  9,  8,  8,  9,  0],
        [ 0,  0,  0, 10,  0,  0, 10],
        [ 0,  0,  0,  0,  6,  8,  0]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [25]:
tensor = torch.randint(0, 100, (20,))
print(tensor)

second_value = tensor[1]
print(second_value)

index = tensor.nonzero()[1].item()
print(index)

tensor([75, 96, 25, 54, 50, 24,  4,  9, 12, 43, 93, 47, 53, 41, 27, 28, 55, 28,
        14, 37])
tensor(96)
1


Note that the nonzero() method returns a tensor of shape (1, n) where n is the number of non-zero values, so to get the index we need to access the first (and only) item in the second dimension using the [1].item() operator.

In [26]:
index = torch.where(tensor == second_value)[0][0].item()
print(index)

1


Note that the torch.where() function returns a tensor of shape (n, 1) where n is the number of values that meet the condition, so to get the index we need to access the first (and only) item in the first dimension using the [0][0].item() operator.

In [ ]:
# sort

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [29]:
base = torch.arange(1, 8)
tensor = base + 10 * torch.arange(0, 11).view(-1, 1)
print(tensor)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])


Note that the view(-1, 1) method is used to reshape the 1-dimensional tensor torch.arange(0, 11) into a 2-dimensional tensor of shape (11, 1). This allows us to use broadcasting to add it to the base tensor, which has shape (7,).

This will add 10 to each element in each row of the tensor, effectively creating the desired pattern.

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [30]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])

result = a_2d - b_1d.view(-1, 1)
print(result)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])


Note that the view(-1, 1) method is used to reshape the 1-dimensional tensor b_1d into a 2-dimensional tensor of shape (3, 1), allowing us to perform broadcasting subtraction with the 2-dimensional tensor a_2d. This will subtract each element of b_1d from all elements of the corresponding rows of a_2d.

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

In [31]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

matching_indexes = (a == b).nonzero().squeeze()
print(matching_indexes)

tensor([1, 3, 5, 7])


The nonzero() method is used to get the indices where the elements of a and b match. The squeeze() method is used to remove any singleton dimensions from the resulting tensor. This will give us the indexes for which elements of a and b match, in this case [1, 3, 5, 7].

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [55]:
tensor = torch.arange(9).view(3, 3)
inverted_tensor = tensor.flip(dims=(-2,1))
print(inverted_tensor)

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])


1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [56]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)
result = a[mask]
print(result)

tensor([ 6,  9, 10])


You can use the boolean masking technique to achieve this. Boolean masking involves creating a boolean tensor with the same shape as the input tensor, where each element is True if the corresponding element in the input tensor meets a certain condition, and False otherwise. You can then use the boolean tensor to index into the input tensor and extract only the elements that meet the condition.

1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [61]:
a = torch.arange(9).reshape(3, 3)
print("Original tensor:")
print(a)

a[:, [0, 1]] = a[:, [1, 0]]
print("\nTensor with columns 0 and 1 swapped:")
print(a)

Original tensor:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Tensor with columns 0 and 1 swapped:
tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])


1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [62]:
tensor = torch.randint(0, 11, (8, 10))

# Find the row with the minimum sum
min_sum, min_index = tensor.sum(dim=1).min(dim=0)
min_row = tensor[min_index]

print("The tensor:\n", tensor)
print("\nThe row with the minimum sum:", min_row)
print("Index of the row with the minimum sum:", min_index)

The tensor:
 tensor([[ 2,  7,  8,  7,  3, 10,  9,  5,  0,  2],
        [ 6,  7,  9,  1,  4,  3,  0,  6,  5,  6],
        [ 5,  8,  7,  2,  3,  4, 10,  4,  4,  4],
        [ 5,  9,  8, 10,  9, 10,  8,  2,  2, 10],
        [ 4,  1,  0,  7,  0,  9,  1,  7,  9,  3],
        [ 7,  1,  4,  4,  7,  4,  5,  6,  0,  6],
        [ 6,  4,  7,  6,  8,  5,  8,  4,  8,  3],
        [ 1,  3,  8,  9,  5,  9,  0,  8,  8,  6]])

The row with the minimum sum: tensor([4, 1, 0, 7, 0, 9, 1, 7, 9, 3])
Index of the row with the minimum sum: tensor(4)


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [63]:
# Create a tensor from 20 random integers from 0 to 100
tensor = torch.randint(0, 101, (20,))

# Trim values from below by value 30 and from above by value 70
tensor = torch.clamp(tensor, 30, 70)

print("Tensor with trimmed values:", tensor)

Tensor with trimmed values: tensor([53, 30, 30, 70, 70, 30, 70, 30, 70, 32, 63, 70, 70, 43, 49, 59, 70, 68,
        30, 62])


1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [64]:
tensor1 = torch.randint(0, 11, (30, 3))
tensor2 = torch.randint(0, 11, (30, 3))

result = tensor1[tensor1 > tensor2]

sum_result = result.sum()
print("Sum of values in tensor1 greater than corresponding values in tensor2: ", sum_result)

Sum of values in tensor1 greater than corresponding values in tensor2:  tensor(282)


In this example, tensor1 and tensor2 are created from random integers from 0 to 10. The comparison tensor1 > tensor2 creates a boolean tensor indicating which elements of tensor1 are greater than the corresponding elements of tensor2. Finally, we select these elements from tensor1 using boolean indexing and calculate their sum.

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [81]:
a = torch.randint(0, 11, (20, 20))

# Get the indices of elements above the main diagonal
idx = torch.triu_indices(20, 20, 1)

# Use the indices to extract the elements above the main diagonal
result = a[idx[0], idx[1]]

print(result)

tensor([10,  0,  6,  4,  9,  9,  2,  7,  2,  7,  7, 10,  8,  2,  5,  1, 10, 10,
         6,  8,  7,  3,  0,  1,  3,  0,  4,  1,  7, 10,  2,  3,  2,  5,  6,  3,
         8,  7,  0,  2, 10,  1,  7,  5,  0,  5,  0,  6, 10,  4,  6,  7,  9,  8,
         3,  6,  2,  3, 10,  1, 10,  4,  0,  2,  8,  5,  7,  7,  4,  9,  0,  2,
         2,  5,  5, 10,  9, 10,  1,  1,  4,  9,  1,  2,  9,  8,  5,  5,  3,  0,
        10,  4,  9,  0,  5,  2,  9,  4,  6,  7,  8,  3, 10,  1,  9,  9,  2,  3,
         9,  8,  2,  5,  7,  6,  7,  4,  9, 10,  1,  4,  3,  3,  3,  1, 10, 10,
         0, 10,  5, 10,  5,  3,  7,  4,  3,  8,  7,  8,  4,  1,  4,  3,  8,  5,
         5,  4,  2,  5,  6,  5,  5,  1,  5,  6,  4,  9,  2, 10, 10,  8, 10,  3,
         4,  6,  7,  6,  2,  8,  2,  1,  4,  9, 10,  0,  3,  5,  3,  8,  7,  4,
         8,  7,  1,  9,  7,  0,  0,  5,  8,  0])


In this example, the torch.triu_indices function is used to get the indices of the elements above the main diagonal, and then those indices are used to extract the corresponding elements from a.

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [88]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))

indices = (ar1 == ar2)
ar1[indices] *= 2

ar1

tensor([[ 3,  2,  9, 10,  6,  7,  1,  9, 10,  3],
        [ 7,  0, 10,  7,  8,  7,  9,  2,  9,  5],
        [ 4,  1,  6,  0, 10,  8,  7,  4,  9, 10],
        [10,  1, 10,  2,  5,  7,  6,  9,  6,  1],
        [ 1,  7,  8,  2, 16,  4,  9,  9,  4,  3]])

In this example, indices is a tensor of size (5, 10) that contains True values at positions where the elements of ar1 and ar2 are equal. The line ar1[indices] *= 2 doubles all values in ar1 at positions where the corresponding values in indices are True.

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [90]:
# Generating three tensors with random integers
ar1 = torch.randint(low=0, high=11, size=(4, 7))
ar2 = torch.randint(low=0, high=11, size=(4, 7))
ar3 = torch.randint(low=0, high=11, size=(4, 7))

# Zeroing out elements of ar1 that are greater than ar2 and fewer than ar3
ar1[(ar1 > ar2) & (ar1 < ar3)] = 0

ar1

tensor([[ 8,  3,  4,  8,  8, 10,  6],
        [ 0,  2,  0,  0, 10, 10, 10],
        [ 5,  3,  9,  2,  8, 10,  5],
        [ 9, 10,  2,  5,  9, 10,  9]])

After this code, ar1 will be a tensor with zeros in place of the elements that were greater than corresponding ar2 elements and fewer than corresponding ar3 elements.

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [119]:
ar1 = torch.randint(0, 21, (20, 5))
column_counts = torch.zeros(5)
print(ar1)

for i in range(20):
    row_max = ar1[i].max().item()
    # print(row_max)
    for j in range(5):
        if ar1[i][j].item() == row_max:
            print(ar1[i][j].item(), row_max)
            column_counts[j] += 1
            
print(column_counts)
result = []
for i in range(5):
    if column_counts[i] >= 5:
        result.append(i)
        
print("Columns with the maximum value occurring at least 5 times:", result)

tensor([[18, 15, 10,  1,  9],
        [ 6,  0, 14, 17,  9],
        [ 8,  9,  5, 11, 12],
        [14,  7,  0, 10, 12],
        [ 1, 16, 16, 20,  9],
        [ 0,  7,  6, 10, 16],
        [17,  6, 17,  6, 18],
        [19, 12, 18,  6,  9],
        [ 7,  4, 17, 11,  3],
        [10, 10,  2, 10,  4],
        [20, 18,  8, 20, 12],
        [19, 14,  9, 19,  3],
        [ 7, 13,  6,  7, 18],
        [18,  8, 15, 17,  1],
        [19,  0,  5,  5, 20],
        [11, 19, 17, 17, 20],
        [ 6,  9,  6,  8, 19],
        [19, 10, 16,  9,  7],
        [20,  9,  5, 15,  3],
        [17, 15, 20,  5, 12]])
18 18
17 17
12 12
14 14
20 20
16 16
18 18
19 19
17 17
10 10
10 10
10 10
20 20
20 20
19 19
19 19
18 18
18 18
20 20
20 20
19 19
19 19
20 20
20 20
tensor([9., 1., 2., 5., 7.])
Columns with the maximum value occurring at least 5 times: [0, 3, 4]


This code first creates a tensor ar1 of random integers from 0 to 20, and then creates an all-zero tensor column_counts to store the count of the maximum value in each column.

Next, it loops through the rows of ar1 and finds the maximum value in each row. For each column where the maximum value occurs, it increments the corresponding count in column_counts.

Finally, it loops through column_counts and finds the columns where the count is greater than or equal to 5, and appends the column indices to a list result.

The final result is the list of columns where the maximum value occurs at least 5 times.

In [183]:
columns = []

while len(columns) == 0:
    ar1 = torch.randint(0, 21, (20, 5))
    for j in range(5):
        column = ar1[:, j]
        count = (column == column.max()).sum().item()
        if count >= 5:
            columns.append(j)
    # print(ar1)
print(ar1)
print(columns)

tensor([[ 3, 19, 19, 18, 18],
        [15,  0, 16, 16,  8],
        [ 7,  8, 11,  5,  3],
        [16,  7, 18,  6, 20],
        [13, 20, 10,  2, 16],
        [16, 20, 15,  5,  5],
        [10, 15, 18, 19, 17],
        [20, 11, 20, 13, 13],
        [ 8, 12, 14, 10, 18],
        [14, 10,  7, 11,  6],
        [ 4, 17, 17,  1, 10],
        [20,  8, 19,  0, 10],
        [19,  6,  6, 14, 13],
        [20,  3, 17, 10, 12],
        [17, 16, 14,  2,  0],
        [20,  7, 10,  4, 18],
        [ 1, 12, 11,  4,  0],
        [ 1, 12, 17, 14, 16],
        [20, 10,  9, 20,  5],
        [14, 11, 10, 15,  8]])
[0]


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [278]:
# Create the tensor with random values from 0 to 1
ar1 = torch.rand(4, 7)
print(ar1)

# Find the indices of the maximum element in the tensor
max_index = torch.argmax(ar1)
max_row, max_col = max_index // 7, max_index % 7
print(max_index, max_row, max_col)
# Zero out all values below and to the right of the maximum value
# ar1[max_row+1:, max_col] = 0
# ar1[max_row:, max_col+1:] = 0 
ar1[max_row+1:, :] = 0
ar1[:, max_col+1:] = 0


print(ar1)

tensor([[0.3817, 0.4456, 0.0995, 0.9099, 0.3797, 0.7550, 0.3889],
        [0.5984, 0.5159, 0.9316, 0.1749, 0.3579, 0.5192, 0.4774],
        [0.0694, 0.1671, 0.7544, 0.8224, 0.4871, 0.5400, 0.8227],
        [0.6426, 0.8876, 0.8393, 0.4926, 0.5668, 0.2524, 0.8824]])
tensor(9) tensor(1) tensor(2)
tensor([[0.3817, 0.4456, 0.0995, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5984, 0.5159, 0.9316, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


This code creates a two-dimensional tensor ar1 of shape (4, 7) with random values ranging from 0 to 1. The maximum value in the tensor is found using the torch.argmax() function, which returns the index of the maximum value in the tensor. The max_row and max_col variables store the row and column of the maximum value, respectively.

Finally, we set all values in the tensor that are located below and to the right of the maximum value to zero using slicing and assignment. The resulting tensor is printed to verify that the values have been set to zero as expected.

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [304]:
# Input tensor
x = torch.tensor([2, 3, 2, 2, 2, 1])

def one_hot_encode_tensor(x):
    # Determine the maximum value
    max_val = x.max()

    # Create a tensor with shape [len(x), max_val] filled with zeros
    one_hot = torch.zeros((len(x), max_val), dtype=torch.float32)

    # Use indexing to set the appropriate values to 1
    for i in range(len(x)):
        one_hot[i, x[i]-1] = 1

    # Return the one-hot encoded tensor
    return one_hot

one_hot_encode_tensor(x)

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [319]:

# Create the tensor with random integers from 0 to 100
arr = torch.tensor([71, 83, 40, 27, 36, 13,  7, 72,  7, 49, 43, 36, 38, 90,  5, 61, 93, 35,
        96, 23])
print("Tensor: ", arr)

# Find the most frequent value in the tensor
value, count = torch.mode(arr)
print("Most frequent value: ", value.item())
print("Number of occurrences: ", count.item())

# Find the indices corresponding to the most frequent value
indices = torch.where(arr == value.item())[0]
print("Indices of the most frequent value: ", indices)

# In case of tie for the two values with highest occurrences,
# the algorithm will return the first one found in the tensor.
# If a different behavior is desired, it can be implemented by
# sorting the tensor and counting the occurrences of each unique value,
# then finding the two values with the highest count and using both of them in the one-hot encoding

Tensor:  tensor([71, 83, 40, 27, 36, 13,  7, 72,  7, 49, 43, 36, 38, 90,  5, 61, 93, 35,
        96, 23])
Most frequent value:  7
Number of occurrences:  8
Indices of the most frequent value:  tensor([6, 8])


In [316]:
# arr = torch.randint(0, 101, (20,))
arr = torch.tensor([71, 83, 40, 27, 37, 13,  7, 72,  7, 49, 5, 36, 38, 90,  5, 61, 93, 35,
        96, 23])
print(arr)

# Find the most frequent value in the tensor
values, counts = torch.unique(arr, return_counts=True)
print(values, counts)
most_frequent_value = values[counts.argmax()]
print("Most frequent value: ", most_frequent_value)

# Find the indices in the tensor corresponding to the most frequent value
indices = torch.where(arr == most_frequent_value)[0]
print("Indices: ", indices)

tensor([71, 83, 40, 27, 37, 13,  7, 72,  7, 49,  5, 36, 38, 90,  5, 61, 93, 35,
        96, 23])
tensor([ 5,  7, 13, 23, 27, 35, 36, 37, 38, 40, 49, 61, 71, 72, 83, 90, 93, 96]) tensor([2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
Most frequent value:  tensor(5)
Indices:  tensor([10, 14])


This code generates a 1D tensor arr containing 20 random integers from 0 to 100. It then uses the torch.unique function to find the unique values in the tensor and their count of occurrences. The most frequent value is determined by finding the maximum count and its corresponding value. Finally, the indices corresponding to the most frequent value are found using torch.where function.

In the case where there are two values with the highest occurrence, the code will return the indices of one of the values. The acceptable behavior of the algorithm would be to return the indices of both values, as both of them are equally frequent in the tensor.

In [331]:
# Create a tensor with 20 random integers from 0 to 100
arr = torch.randint(0, 101, (20,))
print("Tensor: ", arr)

# Find the unique values in the tensor and their counts
unique_vals, counts = torch.unique(arr, return_counts=True)

# Sort the count tensor in descending order and find the two values with the highest counts
sorted_counts, indices = torch.sort(counts, descending=True)
first_max = unique_vals[indices[0]]
second_max = unique_vals[indices[1]] if sorted_counts[0] == sorted_counts[1] else None
print("First max: ", first_max, "Count: ", sorted_counts[0])
print("Second max: ", second_max, "Count: ", sorted_counts[1])

# Create a tensor to store the one-hot encoded values for the first max value
one_hot_1 = (arr == first_max).float()
print("One-hot encoding for first max: ", one_hot_1)
print(f"Indexes: {torch.where(one_hot_1 == one_hot_1.max())[0]}")

# Create a tensor to store the one-hot encoded values for the second max value, if it exists
if second_max is not None:
    one_hot_2 = (arr == second_max).float()
    print("One-hot encoding for second max: ", one_hot_2)
    print(f"Indexes: {torch.where(one_hot_2 == one_hot_2.max())[0]}")

Tensor:  tensor([79, 88, 37,  7, 83, 88, 69, 43, 75, 93, 23, 47, 83, 53, 37, 23, 95, 47,
         1, 41])
First max:  tensor(23) Count:  tensor(2)
Second max:  tensor(37) Count:  tensor(2)
One-hot encoding for first max:  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
        0., 0.])
Indexes: tensor([10, 15])
One-hot encoding for second max:  tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0.])
Indexes: tensor([ 2, 14])


In [335]:
# Create a tensor with 20 random integers from 0 to 100
arr = torch.randint(0, 100, (20,))

# Find the most frequent value
value, count = torch.mode(arr)

# Get the indices of the most frequent value
indices = (arr == value).nonzero()

print("Tensor:", arr)
print("Most frequent value:", value)
print("Count of most frequent value:", count)
print("Indices of most frequent value:", indices)

Tensor: tensor([16, 56, 87, 70, 28, 62,  0, 23, 44, 69, 95,  5, 36,  6,  7, 87, 33,  0,
        40, 42])
Most frequent value: tensor(0)
Count of most frequent value: tensor(6)
Indices of most frequent value: tensor([[ 6],
        [17]])


This code first finds the unique values and their counts in the arr tensor using the torch.unique function. It then sorts the count tensor in descending order and finds the two values with the highest counts. If the two values have the same count, it stores the second max value in the second_max variable, otherwise it sets second_max to None. Finally, it creates two separate one-hot encoded tensors, one_hot_1 for the first max value and one_hot_2 for the second max value (if it exists), by using the equality operator == and casting the result to a float tensor.

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [344]:
import numpy as np

def func(x):
    return x * np.sin(x)

def bisect(a, b):
    eps = 0.01 * (b - a)
    mid = (a + b) / 2
    while abs(func(mid) - 0.5) >= eps:
        if func(mid) > 0.5:
            b = mid
        else:
            a = mid
        mid = (a + b) / 2
    return mid

a, b = 0, 10
x = bisect(a, b)
print("The solution is approximately x =", x)

The solution is approximately x = 6.3671875


The bisection method is an iterative method that works by repeatedly dividing the interval in half until the solution is found. In each iteration, the midpoint of the interval is calculated and compared to the target value (0.5 in this case). The interval is then updated to exclude the half of the interval where the solution is not likely to be found. This continues until the error is less than 1% of the interval width.

In [357]:
import numpy as np
from scipy.optimize import minimize_scalar

def func(x):
    return x * np.sin(x) - 0.5

result = minimize_scalar(func, bounds=(0, 10), method='bounded')
print(result)
x_opt = result.x

print("The value of x where x * sin(x) is approximately equal to 0.5 is:", x_opt)

     fun: -5.314469889712029
 message: 'Solution found.'
    nfev: 11
     nit: 11
  status: 0
 success: True
       x: 4.913180742808922
The value of x where x * sin(x) is approximately equal to 0.5 is: 4.913180742808922


1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 